import pickle
import numpy as np
import pandas as pd
class metapop1:
    def __init__(self, settings):
        self.envID = 'metapop1'
        # if settingID is in the settings variable, load 
        if 'settingID' in settings:
            filename = 'envsetting.csv'
            settings_df = pd.read_csv(filename)
            # which row has settingID that matches settings['settingID']?
            self.settingID = settings['settingID']
            setting_row = settings_df[settings_df['ID'] == self.settingID].index[0]
            self.partial_observability = settings_df['partial_observability'].iloc[setting_row]
            self.patchnum = settings_df['patchnum'].iloc[setting_row]
            self.action_portfolio = settings_df['action_portfolio'].iloc[setting_row] # 0= restoration and supplementation, 1= restoration only, 2= supplementation only
            self.survey_is_action = settings_df['survey_is_action'].iloc[setting_row] # 0= survey is not an action, 1= survey is an action
            self.dispersal_regime = settings_df['dispersal_regime'].iloc[setting_row] # 0= no dispersal regimes, 1= Z
            self.terminal_penalty = settings_df['terminal_penalty'].iloc[setting_row] # 0= no terminal penalty, 1= terminal penalty per extinct patch
            self.dispersaltype = settings_df['dispersal_type'].iloc[setting_row] # dispersal weight generation method 0= uniform, 1= graph-based 
            self.dispersalID = settings_df['dispersal_ID'].iloc[setting_row] # dispersal weight ID for uniform dispersal weights, which corresponds to the index of the weight matrix in the collection of weights generated by dispersal_weight_generator.py.
            self.paramsetID = settings_df['paramsetID'].iloc[setting_row] # parameter set ID, which corresponds to the index of the parameter set in the metapop_paramset.csv file.
            self.kR = settings_df['kR'].iloc[setting_row] # maximum number of patches that can be restored in one time step 
            self.kS = settings_df['kS'].iloc[setting_row] # maximum number of patches that can be supplemented in one time step
            self.dim2state = settings_df['dim2state'].iloc[setting_row] # whether state is 2 dimensional (patchnum, variable)
            self.dim2state_with_C = settings_df['dim2state_with_C'].iloc[setting_row] # whether state is 2 dimensional with connectivity (patchnum, variable) or (patchnum, variable+connectivity)
        else:
            self.settings = settings
            self.partial_observability = settings['partial_observability']
            self.patchnum = settings['patchnum']
            self.action_portfolio = settings['action_portfolio'] # 0= restoration and supplementation, 1= restoration only, 2= supplementation only
            self.survey_is_action = settings['survey_is_action'] # 0= survey is not an action, 1= survey is an action
            self.dispersal_regime = settings['dispersal_regime'] # 0= no dispersal regimes, 1= Z
            self.terminal_penalty = settings['terminal_penalty'] # 0= no terminal penalty, 1= terminal penalty per extinct patch
            self.dispersaltype = settings['dispersal_type'] # dispersal weight generation method 0= uniform, 1= graph-based 
            self.dispersalID = settings['dispersal_ID'] # dispersal weight ID for uniform dispersal weights, which corresponds to the index of the weight matrix in the collection of weights generated by dispersal_weight_generator.py.
            self.paramsetID = settings['paramsetID'] # parameter set ID, which corresponds to the index of the parameter set in the metapop_paramset.csv file.
            self.kR = settings['kR'] # maximum number of patches that can be restored in one time step 
            self.kS = settings['kS'] # maximum number of patches that can be supplemented in one time step
            self.dim2state = settings['dim2state'] # whether state is 2 dimensional (patchnum, variable)
            self.dim2state_with_C = settings['dim2state_with_C'] # whether state is 2 dimensional with connectivity (patchnum, variable) or (patchnum, variable+connectivity)

        # parameters
        paramsetfilename = 'metapop_paramset.csv'
        paramset = pd.read_csv(paramsetfilename)
        self.deltaH = paramset['deltaH'].iloc[self.paramsetID] # probability of habitat being degraded
        self.Ztrans = np.array([[paramset['p00'].iloc[self.paramsetID],paramset['p01'].iloc[self.paramsetID]],[paramset['p10'].iloc[self.paramsetID],paramset['p11'].iloc[self.paramsetID]]]) # transition matrix for dispersal regime Z
        self.alph0 = paramset['alph0'].iloc[self.paramsetID] # colonization parameter
        self.alphZ = paramset['alphZ'].iloc[self.paramsetID] # colonization parameter related to dispersal regime Z
        self.alphH = paramset['alphH'].iloc[self.paramsetID] # colonization parameter related to habitat quality
        self.beta0 = paramset['beta0'].iloc[self.paramsetID] # extinction parameter
        self.betaH = paramset['betaH'].iloc[self.paramsetID] # extinction parameter related to habitat quality
        self.qs = paramset['qs'].iloc[self.paramsetID] # probability of successful supplementation
        self.pdet = paramset['pdet'].iloc[self.paramsetID] # probability of detection in partially observable system
        self.pfp = paramset['pfp'].iloc[self.paramsetID] # probability of false positive in partially observable system
        self.L = paramset['L'].iloc[self.paramsetID] # terminal penalty per extinct patch.
        self.T = paramset['T'].iloc[self.paramsetID] # time horizon
        self.B = paramset['B'].iloc[self.paramsetID] # budget. number of surveys that can be taken.
        self.cr = paramset['cr'].iloc[self.paramsetID] # cost of restoration
        self.cs = paramset['cs'].iloc[self.paramsetID] # cost of supplementation
        if self.dispersaltype == 'uniform':
            with open(f'./dispersal_weights/uniform_dispersal_weights_patchnum{self.patchnum}.pkl', 'rb') as f:
                weights_collection = pickle.load(f)
            self.w = weights_collection[self.dispersalID] # dispersal weights between patches
        elif self.dispersaltype == 'graph-based':
            with open(f'./dispersal_weights/graph_dispersal_weights.pkl', 'rb') as f:
                weights_collection = pickle.load(f)
            self.w = weights_collection
        
        self.incoming_w = np.sum(self.w, axis=0) # incoming dispersal weight for each patch

        # set dimensions
        ## state variables: S = occupancy state, H = habitat quality, M = survey mark, Z = dispersal regime
        self.X_dim = (self.patchnum) # state dimension
        self.H_dim = (self.patchnum) # habitat quality dimension
        self.Z_dim = (1)
        ## observation variables: Y = survey observation
        self.M_dim = (self.patchnum) # survey mark dimension
        self.Y_dim = (self.patchnum) # dispersal regime dimension
        ## action variables: aR = restoration action, aS = supplementation action
        self.aR_dim = (self.patchnum) # restoration action dimension
        self.aS_dim = (self.patchnum) # supplementation action dimension
        self.aY_dim = (self.patchnum) # survey action dimension, if survey is an action
        ## time dimension (only if terminal penalty is applied)
        self.t_dim = (1)
        # dimensions
        ## dimensions by variables
        if self.partial_observability == 1:
            self.statevar_dim = [self.X_dim, self.H_dim, self.M_dim]
            self.obsvar_dim = [self.Y_dim, self.H_dim, self.M_dim]
            self.sidx = {'X': np.arange(self.X_dim), 'H': np.arange(self.H_dim)+self.X_dim, 'M': np.arange(self.M_dim)+self.X_dim+self.H_dim}
            self.oidx = {'Y': np.arange(self.Y_dim), 'H': np.arange(self.H_dim)+self.Y_dim, 'M': np.arange(self.M_dim)+self.Y_dim+self.H_dim}
        else:
            self.statevar_dim = [self.X_dim, self.H_dim]
            self.obsvar_dim = [self.X_dim, self.H_dim]
            self.sidx = {'X': np.arange(self.X_dim), 'H': np.arange(self.H_dim)+self.X_dim}
            self.oidx = {'X': np.arange(self.X_dim), 'H': np.arange(self.H_dim)+self.X_dim}
        
        if self.dispersal_regime == 1:
            self.statevar_dim.append(self.Z_dim)
            self.obsvar_dim.append(self.Z_dim)
            if self.partial_observability == 1:
                self.sidx['Z'] = np.arange(self.Z_dim)+self.X_dim+self.H_dim+self.M_dim
                self.sidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim+self.M_dim+self.Z_dim
                self.oidx['t'] = np.arange(self.t_dim)+self.Y_dim+self.H_dim+self.M_dim
            else:
                self.sidx['Z'] = np.arange(self.Z_dim)+self.X_dim+self.H_dim
                self.oidx['Z'] = np.arange(self.Z_dim)+self.Y_dim+self.H_dim
                self.sidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim+self.Z_dim
                self.oidx['t'] = np.arange(self.t_dim)+self.Y_dim+self.H_dim+self.Z_dim
        else:
            self.sidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim
            self.oidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim
        if self.dim2state == 1: # corect sidx and oidx  if dim2state ==1
            if self.partial_observability == 1:
                self.sidx = {'X': 0, 'H': 1, 'M': 2, 'C': 3, 'Z': 3+self.dim2state_with_C, 't': 4+self.dim2state_with_C} if self.dispersal_regime == 1 else {'X': 0, 'H': 1, 'M': 2, 't': 3+self.dim2state_with_C}
                self.oidx = {'Y': 0, 'H': 1, 'M': 2, 'C': 3,'Z': 3+self.dim2state_with_C, 't': 4+self.dim2state_with_C} if self.dispersal_regime == 1 else {'Y': 0, 'H': 1, 'M': 2, 't': 3+self.dim2state_with_C}
            else:
                self.sidx = {'X': 0, 'H': 1, 'Z': 2+self.dim2state_with_C, 't': 3+self.dim2state_with_C} if self.dispersal_regime == 1 else {'X': 0, 'H': 1, 't': 2+self.dim2state_with_C}
                self.oidx = {'X': 0, 'H': 1, 'Z': 2+self.dim2state_with_C, 't': 3+self.dim2state_with_C} if self.dispersal_regime == 1 else {'X': 0, 'H': 1, 't': 2+self.dim2state_with_C}
        self.statevar_dim.append(self.t_dim)
        self.obsvar_dim.append(self.t_dim)

        if self.action_portfolio == 0:
            self.action_dim = [self.aR_dim, self.aS_dim]
        elif self.action_portfolio == 1:
            self.action_dim = [self.aR_dim]
        elif self.action_portfolio == 2:
            self.action_dim = [self.aS_dim]
        if self.survey_is_action == 1:
            self.action_dim.append(self.aY_dim)
        
        self.action_dim = tuple(self.action_dim)

        
        ## dimensions by space
        self.statespace_dim = np.sum(self.statevar_dim)
        self.obsspace_dim = np.sum(self.obsvar_dim)
        self.actionspace_dim = np.sum(self.action_dim)
        if self.dim2state == 1:
            self.statefeature_dim = 2 + self.partial_observability + self.dispersal_regime + self.dim2state_with_C + 1
            self.obsfeature_dim = 2 + self.partial_observability + (self.dispersal_regime if self.partial_observability==0 else 0) + self.dim2state_with_C + 1
            self.statespace_dim = (self.patchnum, self.statefeature_dim) # add connectivity to state space if dim2state_with_C is 1
            self.obsspace_dim = (self.patchnum, self.obsfeature_dim) # add connectivity to observation space if dim2state_with_C is 1
        ## variable indexes
        if self.action_portfolio == 0:
            self.aidx = {'aR': np.arange(self.aR_dim), 'aS': np.arange(self.aS_dim)+self.aR_dim}
        elif self.action_portfolio == 1:
            self.aidx = {'aR': np.arange(self.aR_dim)}
        elif self.action_portfolio == 2:
            self.aidx = {'aS': np.arange(self.aS_dim)}
        if self.survey_is_action == 1:
            self.aidx['aY'] = np.arange(self.aY_dim)+self.aidx[list(self.aidx.keys())[-1]][-1]+1

        # some heuristics variables
        # heur2
        self.eprob_th = 0.5
        self.cprob_th = 0.5
        # heur3
        self.s_th = 0.5 # supplementation threshold: only supplement if gain_S > s_th * cs
        self.r_th = 0.5 # restoration threshold: only restore if gain_R > r_th * cr
        self.w_ext = 1.0   # importance of reducing extinction in heuristics
        self.w_col = 0.5   # importance of increasing colonization in heuristics
        # heur4 
        self.w1 = 1.0        # weight on centrality
        self.w2 = 1.0        # penalty on colonization probability
        self.tau_supp = 0.0  # supplementation threshold
        
        # initialize state and observation
        self.obs, self.state = self.reset()

    def reset(self):
        self.obs = np.zeros(np.sum(self.statevar_dim))
        self.state = np.zeros(np.sum(self.obsvar_dim))

        X = np.random.choice([0,1], size=self.X_dim, p=[0.3,0.7]) # initial occupancy state
        H = np.random.choice([0,1], size=self.H_dim, p=[self.deltaH, 1-self.deltaH]) # initial habitat quality
        Z = np.random.choice([0,1], size=self.Z_dim, p=[self.Ztrans[0,0], self.Ztrans[1,0]]) # initial dispersal regime
        if self.partial_observability == 1:
            M, Y = self.survey(X) # initial survey observation
            if self.dispersal_regime == 1:
                self.state = np.concatenate([X,H,M,Z,[0]])
            else: 
                self.state = np.concatenate([X,H,M,[0]])
            self.obs = np.concatenate([Y,H,M,[0]])
        else:
            if self.dispersal_regime == 1:
                self.state = np.concatenate([X,H,Z,[0]])
                self.obs = np.concatenate([X,H,Z,[0]])
            else:
                self.state = np.concatenate([X,H,[0]])
                self.obs = np.concatenate([X,H,[0]])
        if self.dim2state == 1:
            self.state, self.obs = self.change_to_2D(connectivity=self.w @ X, Z_next=Z if self.dispersal_regime == 1 else None, t=0)
        return self.obs, self.state
    
    def step(self, action):
        info = {}
        if self.action_portfolio == 0:
            aR = action[self.aidx['aR']]
            aS = action[self.aidx['aS']]
        elif self.action_portfolio == 1:
            aR = action[self.aidx['aR']]
            aS = np.zeros(self.aS_dim, dtype=int)
        elif self.action_portfolio == 2:
            aR = np.zeros(self.aR_dim, dtype=int)
            aS = action[self.aidx['aS']]
        aY = action[self.aidx['aY']] if self.survey_is_action == 1 else np.zeros(self.aY_dim, dtype=int)
        if self.dim2state == 0:
            X = self.state[self.sidx['X']]
            H = self.state[self.sidx['H']]
            if self.dispersal_regime == 1:
                Z = self.state[self.sidx['Z']][0]
            else:
                Z = 0
            t = self.state[self.sidx['t']][0]
        else:
            X = self.state[:,self.sidx['X']]
            H = self.state[:,self.sidx['H']]
            if self.dispersal_regime == 1:
                Z = int(self.state[0,self.sidx['Z']])
            else:
                Z = 0
            t = self.state[0,self.sidx['t']]
        # calculate colonization and extinction probabilities based on current state and parameters
        connectivity = self.w @ X # connectivity for each patch based on current occupancy and dispersal weights
        cprob = 1 - np.exp(-self.alph0 * connectivity * (1 + self.alphZ * Z) * (1 + self.alphH * H))
        eprob = (1/(1+np.exp(-(self.beta0 - self.betaH * H)))) * (1 - cprob)
        # update state based on actions and transition probabilities
        ## occupancy 
        X_next = np.zeros(self.X_dim, dtype=int)
        mask = X==0
        mask2 = ~mask
        X_next[mask] = np.random.binomial(1, cprob[mask]) + aS[mask] * np.random.binomial(1, self.qs, size=np.sum(mask))
        X_next[mask2] = np.random.binomial(1, 1 - eprob[mask2]) + aS[mask2] * np.random.binomial(1, self.qs, size=np.sum(mask2))
        X_next = np.minimum(X_next, 1)
        ## habitat quality
        H_next = np.zeros(self.H_dim, dtype=int)
        H_next[aR==1] = 1
        mask = (aR == 0) & (H == 1)
        H_next[mask] = np.random.choice([0,1], size=np.sum(mask), p=[self.deltaH, 1-self.deltaH])
        ## dispersal regime
        if self.dispersal_regime == 1:
            Z_next = np.random.choice([0,1], size=self.Z_dim, p=self.Ztrans[:,Z])
        
        # update observaiton based on new state and observation probabilities
        if self.partial_observability == 1:
            M_next, Y_next = self.survey(X_next) if self.survey_is_action == 0 else self.survey(X_next, survey_patches=aY)
            self.state = np.concatenate([X_next, H_next, M_next])
            self.obs = np.concatenate([Y_next, H_next, M_next])            
            if self.dispersal_regime == 1:
                self.state = np.concatenate([self.state, Z_next])
            self.state = np.concatenate([self.state, [t+1]])
            self.obs = np.concatenate([self.obs, [t+1]])
        else:
            self.state = np.concatenate([X_next, H_next])
            self.obs = np.concatenate([X_next, H_next])
            if self.dispersal_regime == 1:
                self.state = np.concatenate([self.state, Z_next, [t+1]])
                self.obs = np.concatenate([self.obs, Z_next, [t+1]])
            else:
                self.state = np.concatenate([self.state, [t+1]])
                self.obs = np.concatenate([self.obs, [t+1]])
        if self.dim2state == 1: 
            new_connectivity = self.w @ X_next
            self.state, self.obs = self.change_to_2D(connectivity=new_connectivity, Z_next=Z_next if self.dispersal_regime == 1 else None, t=t+1)
        # reward
        reward = 1/self.patchnum * np.sum(X_next) - self.cr * np.sum(aR) - self.cs * np.sum(aS) # reward based on number of occupied patches and cost of actions
        # done
        if t == self.T-1:
            reward = reward - self.L * (np.sum(1 - X_next)) if self.terminal_penalty == 1 else reward # add terminal penalty
            done = True
        elif np.sum(X_next) == 0: # all patches are extinct
            done = True
        else:           
            done = False
        info['connectivity'] = connectivity
        info['extinction_prob'] = eprob
        info['colonization_prob'] = cprob
        info['occupied_fraction'] = np.mean(X_next)
        info['goodhabitat_fraction'] = np.mean(H_next)
        info['total_cost'] = self.cr * np.sum(aR) + self.cs * np.sum(aS)
        info['total_benefit'] = 1/self.patchnum * np.sum(X_next)
        return self.obs, reward, done, info

    def change_to_2D(self, connectivity=None, Z_next=None, t=None):
        new_state = np.zeros((self.patchnum, self.statefeature_dim))
        new_obs = np.zeros((self.patchnum, self.obsfeature_dim))
        if self.partial_observability == 1:
            new_state[:,:3] = np.array([self.state[:self.patchnum], self.state[self.patchnum:2*self.patchnum], self.state[2*self.patchnum:3*self.patchnum]]).T
            new_obs[:,:3] = np.array([self.obs[:self.patchnum], self.obs[self.patchnum:2*self.patchnum], self.obs[2*self.patchnum:3*self.patchnum]]).T
            idx = 3 
        else:
            new_state[:,:2] = np.array([self.state[:self.patchnum], self.state[self.patchnum:2*self.patchnum]]).T
            new_obs[:,:2] = np.array([self.obs[:self.patchnum], self.obs[self.patchnum:2*self.patchnum]]).T
            idx = 2
        if self.dim2state_with_C == 1:
            new_state[:,idx] = connectivity
            new_obs[:,idx] = connectivity
            idx += 1
        if self.dispersal_regime == 1:
            new_state[:,idx] = Z_next
            if self.partial_observability == 0:
                new_obs[:,idx] = Z_next
        new_state[:,-1] = t
        new_obs[:,-1] = t
        return new_state, new_obs
        
    def survey(self,X, survey_patches = None):
        M = np.zeros(self.M_dim, dtype=int)
        if self.survey_is_action == 1:
            ones_indices = survey_patches == 1
        else:
            ones_indices = np.random.choice(self.M_dim, size=int(self.B), replace=False)
        M[ones_indices] = 1
        Y = np.zeros(self.Y_dim, dtype=int)
        Y[M==1] = X[M==1] * np.random.choice([1,0], size=np.sum(M), p=[self.pdet, 1-self.pdet]) + (1-X[M==1]) * np.random.choice([1,0], size=np.sum(M), p=[self.pfp, 1-self.pfp]) # initial survey observation
        return M, Y 

    def heuristic_action(self, ruletype=1, info=None):
        '''
        heuristic rule for no dispersal regime, no partial observability, and no terminal penalty.
        ruletype = 1
        * Prioritize patches with higher incoming dispersal weight from all patches
        * no action on the last 2 steps if patch abundance is 10 or 20; no action on the last step if patch abundance is 5.
        - if extinct and bad habitat: restore and supplement
        - if extinct and good habitat and incoming dispersal weight from persisting patches is below w^bar_1: supplement only
        - if persisting and bad habitat and incoming dispersal weight from persisting patches is below w^bar_2: restore and supplement
        - if persisting and bad habitat and incoming dispersal weight from persisting patches is equal or above w^bar_2: restore only
        - if persisting and good habitat: no action

        ruletype = 2
        - restore patches from highest to lowest incoming weights until you run out of restoration actions.
        - from highest incoming weights to lowest incoming weights, 
        supplement persisting patches if extinction prob is greater 
        than x
         OR 
        extinct patches if colonization prob is lower than y.
        Only supplement patches that are good habitat or being restored to good habitat.
        '''

        if self.dim2state == 1:
            X = self.obs[:, self.oidx["X"]]
            H = self.obs[:, self.oidx["H"]]
            t = int(self.obs[0, self.oidx["t"]])
        else:
            X = self.obs[self.oidx["X"]]
            H = self.obs[self.oidx["H"]]
            t = int(self.obs[self.oidx["t"]][0])
        if self.dispersal_regime == 1:
            Z = self.obs[0,self.oidx["Z"]] if self.dim2state == 1 else self.obs[self.oidx["Z"]][0]
        else: 
            Z = 0
        if ruletype == 1:
            # set wbar1 and wbar2 thresholds for heuristic rule based on settingID            
            if self.settingID == 18: # n=5
                wbar1 = 1.6
                wbar2 = 1.6
            elif self.settingID == 20: # n=10 median centrality
                wbar1 = 2.0
                wbar2 = 2.0
            elif self.settingID == 22: # n=10 low centrality
                wbar1 = 1.6
                wbar2 = 1.6
            elif self.settingID == 23: # n=10 high centrality
                wbar1 = 1.6
                wbar2 = 1.6
            elif self.settingID == 21: # n=20 
                wbar1 = 1.8
                wbar2 = 1.8
            
            incoming_w_occupied = np.matmul(self.w, X) # incoming dispersal weight from occupied patches

            # assign actions based on heuristic rule
            noactiontime = self.T - 2 if self.patchnum in [10,20] else self.T - 1
            if t >= noactiontime : # no action on the last few steps
                return np.zeros(self.actionspace_dim, dtype=int)
            else:
                ridx = []
                sidx = []
                aR = np.zeros(self.aR_dim, dtype=int)
                aS = np.zeros(self.aS_dim, dtype=int)
                bothactionidx = []
                for i in range(self.patchnum):
                    if X[i] == 0 and H[i] == 0: # extinct and bad habitat
                        ridx.append(i)
                        sidx.append(i)
                        bothactionidx.append(i)
                    elif X[i] == 0 and H[i] == 1 and incoming_w_occupied[i] <= wbar1: # extinct and good habitat and low incoming dispersal weight
                        sidx.append(i)
                    elif X[i] == 1 and H[i] == 0 and incoming_w_occupied[i] <= wbar2: # persisting and bad habitat and low incoming dispersal weight
                        ridx.append(i)
                        sidx.append(i)
                        bothactionidx.append(i)
                    elif X[i] == 1 and H[i] == 0 and incoming_w_occupied[i] >= wbar2: # persisting and bad habitat and high incoming dispersal weight
                        ridx.append(i)
                # sort by incoming dispersal weight and cut by self.kR and self.kS
                
                newridx = sorted(ridx, key=lambda x: self.incoming_w[x], reverse=True)[:self.kR] if len(ridx) > self.kR else ridx
                newsidx = sorted(sidx, key=lambda x: self.incoming_w[x], reverse=True)[:self.kS] if len(sidx) > self.kS else sidx
                # if patches that have both actions get taken off of one of the actions, they
                # should get taken off of the other action as well.
                for i in bothactionidx:
                    if i in ridx and i not in newridx:
                        if i in newsidx:
                            newsidx.remove(i)
                    elif i in sidx and i not in newsidx:
                        if i in newridx:
                            newridx.remove(i)
                # create action vector
                if len(ridx) > 0:
                    aR[np.array(newridx)] = 1
                if len(sidx) > 0:
                    aS[np.array(newsidx)] = 1
                action = np.concatenate([aR, aS])
                return action

        elif ruletype == 2:
            
            connectivity = self.w @ X # connectivity for each patch based on current occupancy and dispersal weights
            incoming_w =  np.sum(self.w, axis=0) # incoming dispersal weight for each patch
            cprob = 1 - np.exp(-self.alph0 * connectivity * (1 + self.alphZ * Z) * (1 + self.alphH * H))
            eprob = (1/(1+np.exp(-(self.beta0 - self.betaH * H)))) * (1 - cprob)
            # sort patches by incoming dispersal weight. 
            sorted_patches = sorted(range(self.patchnum), key=lambda x: incoming_w[x], reverse=True)
            aR = np.zeros(self.aR_dim, dtype=int)
            aS = np.zeros(self.aS_dim, dtype=int)
            arcount = 0 
            ascount = 0

            if self.settingID == 18: # n=5
                self.eprob_th = 0.9
                self.cprob_th = 0.8
            elif self.settingID == 20: # n=10 median centrality
                self.eprob_th = 0.8
                self.cprob_th = 0.2
            elif self.settingID == 21: # n=20 
                self.eprob_th = 0.8
                self.cprob_th = 0.2
            elif self.settingID == 22: # n=10 low centrality
                self.eprob_th = 0.8
                self.cprob_th = 0.2
            elif self.settingID == 23: # n=10 high centrality
                self.eprob_th = 0.9
                self.cprob_th = 0.2

            if t >= self.T - 2: # no action on the last few steps
                return np.zeros(self.actionspace_dim, dtype=int)
            
            for i in sorted_patches:
                if arcount >= self.kR and ascount >= self.kS: # if we have already allocated all actions, break
                    break
                if X[i] == 1: # if patch is occupied
                    # restoration
                    if H[i] == 0 and arcount < self.kR: # if habitat is bad, restore if we have restoration actions left
                        aR[i] = 1
                        arcount += 1
                    # supplementation
                    if (H[i] == 1 or aR[i] == 1) and eprob[i] > self.eprob_th and ascount < self.kS: # if extinction probability is greater than threshold, supplement if we have supplementation actions left
                        aS[i] = 1
                        ascount += 1
                else: # if patch is unoccupied
                    # restoration
                    if H[i] == 0 and arcount < self.kR: # if habitat is bad, restore if we have restoration actions left
                        aR[i] = 1
                        arcount += 1
                    # supplementation
                    if (H[i] == 1 or aR[i] == 1) and cprob[i] < self.cprob_th and ascount < self.kS: # if habitat is good and colonization probability is low, supplement if we have supplementation actions left
                        aS[i] = 1
                        ascount += 1
            action = np.concatenate([aR, aS])
            return action
        elif ruletype == 3:
            """
            Greedy reward-per-cost heuristic

            - Compute marginal gain for restoration and supplementation
            - Rank actions by gain / cost
            - Select top-kR and top-kS
            """

            if self.settingID == 18: # n=5
                self.s_th = 2.0
                self.r_th = 2.4
                self.w_ext = 2.0
                self.w_col = 1.5
            elif self.settingID == 20: # n=10 median centrality
                self.s_th = 4.0
                self.r_th = 2.9
                self.w_ext = 2.5
                self.w_col = 2.0
            elif self.settingID == 21: # n=20
                self.s_th = 5.0
                self.r_th = 2.9
                self.w_ext = 2.0
                self.w_col = 0.5
            elif self.settingID == 22: # n=10 low centrality
                self.s_th = 4.0
                self.r_th = 2.85
                self.w_ext = 2.0
                self.w_col = 2.0
            elif self.settingID == 23: # n=10 high centrality
                self.s_th = 4.5
                self.r_th = 2.9
                self.w_ext = 2.0
                self.w_col = 1.5
                
            # ===== No action at very end (same logic as yours) =====
            if t >= self.T - 2:
                return np.zeros(self.actionspace_dim, dtype=int)

            # ===== Compute baseline probabilities =====
            connectivity = self.w @ X
            cprob = 1 - np.exp(-self.alph0 * connectivity * (1 + self.alphZ * Z) * (1 + self.alphH * H))
            eprob = (1/(1+np.exp(-(self.beta0 - self.betaH * H)))) * (1 - cprob)

            # ===== Containers =====
            R_scores = np.zeros(self.patchnum)
            S_scores = np.zeros(self.patchnum)

            # ===== Loop over patches =====
            for i in range(self.patchnum):

                # =========================
                # SUPPLEMENTATION GAIN
                # =========================
                if X[i] == 0:
                    gain_S = self.qs * (1 - cprob[i])
                else:
                    gain_S = self.qs * eprob[i]

                S_scores[i] = gain_S / (self.cs + 1e-8)

                # =========================
                # RESTORATION GAIN
                # =========================
                if H[i] == 1:
                    R_scores[i] = 0.0
                    continue

                # simulate H=1
                H_new = 1

                cprob_new = 1 - np.exp(-self.alph0 * connectivity[i] * (1 + self.alphZ * Z) * (1 + self.alphH * H_new))
                eprob_new = (1/(1+np.exp(-(self.beta0 - self.betaH * H_new)))) * (1 - cprob_new)

                delta_ext = eprob[i] - eprob_new
                delta_col = cprob_new - cprob[i]

                gain_R = self.w_ext * delta_ext + self.w_col * delta_col

                R_scores[i] = gain_R / (self.cr + 1e-8)

            # ===== Select top actions =====
            aR = np.zeros(self.aR_dim, dtype=int)
            aS = np.zeros(self.aS_dim, dtype=int)

            # sort indices
            R_idx = np.argsort(-R_scores)
            S_idx = np.argsort(-S_scores)

            # ===== Restoration selection =====
            r_count = 0
            for i in R_idx:
                if r_count >= self.kR:
                    break
                if R_scores[i] > self.r_th:   # only take beneficial actions
                    aR[i] = 1
                    r_count += 1

            # ===== Supplementation selection =====
            s_count = 0
            for i in S_idx:
                if s_count >= self.kS:
                    break
                if S_scores[i] > self.s_th:   # only take beneficial actions
                    aS[i] = 1
                    s_count += 1

            action = np.concatenate([aR, aS])
            return action
        elif ruletype == 4:
            """
            Centrality + Recovery Potential heuristic

            Rule A: Restoration
            - Target H=0 patches
            - Rank by centrality (incoming + outgoing weights)

            Rule B: Supplementation
            - Target X=0 patches
            - Score = w1 * centrality - w2 * colonization_prob
            - Only act if score > tau_supp
            """

            if self.settingID in [18,24,25]: # n=5
                self.w1 =0.92
                self.tau_supp = 0.16
            elif self.settingID in [20,26,27]: # n=10 median centrality
                self.w1 = 0.97
                self.tau_supp = 0.24
            elif self.settingID in [21,28,29]: # n=20
                self.w1 = 0.95
                self.tau_supp = 0.1
            elif self.settingID in [22,30,31]: # n=10 low centrality
                self.w1 = 0.92
                self.tau_supp = 0.22
            elif self.settingID in [23,32,33]: # n=10 high centrality
                self.w1 = 0.98
                self.tau_supp = 0.14
            self.w2 = 1-self.w1
            # ===== Optional: no action late =====
            if t >= self.T - 2:
                return np.zeros(self.actionspace_dim, dtype=int)

            # ===== Connectivity + colonization =====
            connectivity = self.w @ X
            cprob = 1 - np.exp(-self.alph0 * connectivity * (1 + self.alphZ * Z) * (1 + self.alphH * H))

            # ===== CENTRALITY SCORE =====
            # incoming + outgoing weights
            incoming = np.sum(self.w, axis=0)
            centrality = incoming    # S_i^C


            # ===== ACTION ARRAYS =====
            aR = np.zeros(self.aR_dim, dtype=int)
            aS = np.zeros(self.aS_dim, dtype=int)

            # ==================================================
            # RULE A: RESTORATION (H == 0)
            # ==================================================
            restore_candidates = np.where(H == 0)[0]

            if len(restore_candidates) > 0:
                # rank by centrality
                sorted_R = sorted(restore_candidates, key=lambda i: centrality[i], reverse=True)
                # take top kR
                selected_R = sorted_R[:self.kR]
                aR[selected_R] = 1


            # ==================================================
            # RULE B: SUPPLEMENTATION (X == 0)
            # ==================================================
            supplement_candidates = np.where(X == 0)[0]

            S_scores = np.full(self.patchnum, 0.0)
            if len(supplement_candidates) > 0:
                S_scores[supplement_candidates] = (self.w1 * centrality[supplement_candidates]/3) - (self.w2 * cprob[supplement_candidates])
            # sort by score
            sorted_S = np.argsort(-S_scores)

            s_count = 0
            for i in sorted_S:
                if s_count >= self.kS:
                    break
                if i in supplement_candidates and S_scores[i] > self.tau_supp:
                    aS[i] = 1
                    s_count += 1

            # ===== Combine =====
            action = np.concatenate([aR, aS])
            return action
        elif ruletype == 5:
            """
            Post-RL heuristic (V5):
            1) Stop all actions very late.
            2) Stop restoration earlier than supplementation.
            3) Restore degraded patches by structural importance with occupancy bonus.
            4) Supplement extinct patches with good habitat or those restored now.
            """

            # Defaults tuned per environment setting.
            if self.settingID in [18,24,25]:  # n=5
                stop_last_n = 2
                stop_restore_last_n = 7
                rest_w_X = 0.5
                rest_w_W = 2.0
            elif self.settingID in [20,26,27]:  # n=10 median centrality
                stop_last_n = 2
                stop_restore_last_n = 7
                rest_w_X = 0.5
                rest_w_W = 2.0
            elif self.settingID in [21,28,29]:  # n=20
                stop_last_n = 2
                stop_restore_last_n = 9
                rest_w_X = 0.25
                rest_w_W = 4.0
            elif self.settingID in [22,30,31]:  # n=10 low centrality
                stop_last_n = 2
                stop_restore_last_n = 7
                rest_w_X = 0.5
                rest_w_W = 2.0
            elif self.settingID in [23,32,33]:  # n=10 high centrality
                stop_last_n = 2
                stop_restore_last_n = 7
                rest_w_X = 0.5
                rest_w_W = 2.0
            else:
                stop_last_n = 2
                stop_restore_last_n = 2
                rest_w_X = 0.5
                rest_w_W = 2.0

            aR = np.zeros(self.aR_dim, dtype=int)
            aS = np.zeros(self.aS_dim, dtype=int)

            remaining = self.T - t

            # Rule 1: stop all actions in the final steps.
            if remaining <= stop_last_n:
                return np.concatenate([aR, aS])

            # Rule 2: restoration in early/mid game only.
            if remaining > stop_restore_last_n:
                degraded_idx = np.where(H == 0)[0]
                if degraded_idx.size > 0:
                    rest_scores = rest_w_X * X[degraded_idx] + rest_w_W * self.incoming_w[degraded_idx]
                    ranked_local = np.argsort(-rest_scores)
                    selected_local = ranked_local[:min(self.kR, degraded_idx.size)]
                    selected_restore = degraded_idx[selected_local]
                    aR[selected_restore] = 1

            # Rule 3: supplementation for extinct patches with good habitat
            # (or those restored now), capped at supplementation budget.
            supplement_candidates = np.where((X == 0) & ((H == 1) | (aR == 1)))[0]
            if supplement_candidates.size > 0:
                supp_scores = self.incoming_w[supplement_candidates]
                ranked_supp = np.argsort(-supp_scores)
                selected_supp = supplement_candidates[ranked_supp[:min(self.kS, supplement_candidates.size)]]
                aS[selected_supp] = 1

            return np.concatenate([aR, aS])
        else:
            return np.zeros(self.actionspace_dim, dtype=int)
            