import pickle
import numpy as np
import pandas as pd
class metapop1:
    def __init__(self, settings):
        self.envID = 'metapop1'
        self.settings = settings
        self.partial_observability = settings['partial_observability']
        self.patchnum = settings['patchnum']
        self.action_portfolio = settings['action_portfolio'] # 0= restoration and supplementation, 1= restoration only, 2= supplementation only
        self.survey_is_action = settings['survey_is_action'] # 0= survey is not an action, 1= survey is an action
        self.dispersal_regime = settings['dispersal_regime'] # 0= no dispersal regimes, 1= Z
        self.terminal_penalty = settings['terminal_penalty'] # 0= no terminal penalty, 1= terminal penalty per extinct patch
        self.limit_actions = settings['limit_actions'] # 0= no limit on number of patches to take actions on. 1= limit number of patches to take actions on to 1.
        self.dispersaltype = settings['dispersal_type'] # dispersal weight generation method 0= uniform, 1= graph-based 
        self.dispersalID = settings['dispersal_ID'] # dispersal weight ID for uniform dispersal weights, which corresponds to the index of the weight matrix in the collection of weights generated by dispersal_weight_generator.py.
        self.paramsetID = settings['paramsetID'] # parameter set ID, which corresponds to the index of the parameter set in the metapop_paramset.csv file.
        self.kR = settings['kR'] # maximum number of patches that can be restored in one time step 
        self.kS = settings['kS'] # maximum number of patches that can be supplemented in one time step

        # parameters
        paramsetfilename = 'metapop_paramset.csv'
        paramset = pd.read_csv(paramsetfilename)
        self.deltaH = paramset['deltaH'].iloc[self.paramsetID] # probability of habitat being degraded
        self.Ztrans = np.array([[paramset['p00'].iloc[self.paramsetID],paramset['p01'].iloc[self.paramsetID]],[paramset['p10'].iloc[self.paramsetID],paramset['p11'].iloc[self.paramsetID]]]) # transition matrix for dispersal regime Z
        self.alph0 = paramset['alph0'].iloc[self.paramsetID] # colonization parameter
        self.alphZ = paramset['alphZ'].iloc[self.paramsetID] # colonization parameter related to dispersal regime Z
        self.alphH = paramset['alphH'].iloc[self.paramsetID] # colonization parameter related to habitat quality
        self.beta0 = paramset['beta0'].iloc[self.paramsetID] # extinction parameter
        self.betaH = paramset['betaH'].iloc[self.paramsetID] # extinction parameter related to habitat quality
        self.qs = paramset['qs'].iloc[self.paramsetID] # probability of successful supplementation
        self.pdet = paramset['pdet'].iloc[self.paramsetID] # probability of detection in partially observable system
        self.pfp = paramset['pfp'].iloc[self.paramsetID] # probability of false positive in partially observable system
        self.L = paramset['L'].iloc[self.paramsetID] # terminal penalty per extinct patch.
        self.T = paramset['T'].iloc[self.paramsetID] # time horizon
        self.B = paramset['B'].iloc[self.paramsetID] # budget. number of surveys that can be taken.
        if self.dispersaltype == 'uniform':
            with open(f'./dispersal_weights/uniform_dispersal_weights_patchnum{self.patchnum}.pkl', 'rb') as f:
                weights_collection = pickle.load(f)
            self.w = weights_collection[self.dispersalID] # dispersal weights between patches
        elif self.dispersaltype == 'graph-based':
            with open(f'./dispersal_weights/graph_dispersal_weights.pkl', 'rb') as f:
                weights_collection = pickle.load(f)
            self.w = weights_collection
        
        ## set cost of actions a function of patch number
        self.cr = 1/self.patchnum # cost of restoration
        self.cs = 1/self.patchnum # cost of supplementation

        # set dimensions
        ## state variables: S = occupancy state, H = habitat quality, M = survey mark, Z = dispersal regime
        self.X_dim = (self.patchnum) # state dimension
        self.H_dim = (self.patchnum) # habitat quality dimension
        self.Z_dim = (1)
        ## observation variables: Y = survey observation
        self.M_dim = (self.patchnum) # survey mark dimension
        self.Y_dim = (self.patchnum) # dispersal regime dimension
        ## action variables: aR = restoration action, aS = supplementation action
        self.aR_dim = (self.patchnum) # restoration action dimension
        self.aS_dim = (self.patchnum) # supplementation action dimension
        self.aY_dim = (self.patchnum) # survey action dimension, if survey is an action
        ## time dimension (only if terminal penalty is applied)
        self.t_dim = (1)
        # dimensions
        ## dimensions by variables
        if self.partial_observability == 1:
            self.statevar_dim = [self.X_dim, self.H_dim, self.M_dim]
            self.obsvar_dim = [self.Y_dim, self.H_dim, self.M_dim]
            self.sidx = {'X': np.arange(self.X_dim), 'H': np.arange(self.H_dim)+self.X_dim, 'M': np.arange(self.M_dim)+self.X_dim+self.H_dim}
            self.oidx = {'Y': np.arange(self.Y_dim), 'H': np.arange(self.H_dim)+self.Y_dim, 'M': np.arange(self.M_dim)+self.Y_dim+self.H_dim}
        else:
            self.statevar_dim = [self.X_dim, self.H_dim]
            self.obsvar_dim = [self.X_dim, self.H_dim]
            self.sidx = {'X': np.arange(self.X_dim), 'H': np.arange(self.H_dim)+self.X_dim}
            self.oidx = {'X': np.arange(self.X_dim), 'H': np.arange(self.H_dim)+self.X_dim}
        
        if self.dispersal_regime == 1:
            self.statevar_dim.append(self.Z_dim)
            self.obsvar_dim.append(self.Z_dim)
            if self.partial_observability == 1:
                self.sidx['Z'] = np.arange(self.Z_dim)+self.X_dim+self.H_dim+self.M_dim
                self.sidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim+self.M_dim+self.Z_dim
                self.oidx['t'] = np.arange(self.t_dim)+self.Y_dim+self.H_dim+self.M_dim
            else:
                self.sidx['Z'] = np.arange(self.Z_dim)+self.X_dim+self.H_dim
                self.oidx['Z'] = np.arange(self.Z_dim)+self.Y_dim+self.H_dim
                self.sidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim+self.Z_dim
                self.oidx['t'] = np.arange(self.t_dim)+self.Y_dim+self.H_dim+self.Z_dim
        else:
            self.sidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim
            self.oidx['t'] = np.arange(self.t_dim)+self.X_dim+self.H_dim

        self.statevar_dim.append(self.t_dim)
        self.obsvar_dim.append(self.t_dim)

        if self.action_portfolio == 0:
            self.action_dim = [self.aR_dim, self.aS_dim]
        elif self.action_portfolio == 1:
            self.action_dim = [self.aR_dim]
        elif self.action_portfolio == 2:
            self.action_dim = [self.aS_dim]
        if self.survey_is_action == 1:
            self.action_dim.append(self.aY_dim)
        
        self.action_dim = tuple(self.action_dim)

        
        ## dimensions by space
        self.statespace_dim = np.sum(self.statevar_dim)
        self.obsspace_dim = np.sum(self.obsvar_dim)
        self.actionspace_dim = np.sum(self.action_dim)
        ## variable indexes
        if self.action_portfolio == 0:
            self.aidx = {'aR': np.arange(self.aR_dim), 'aS': np.arange(self.aS_dim)+self.aR_dim}
        elif self.action_portfolio == 1:
            self.aidx = {'aR': np.arange(self.aR_dim)}
        elif self.action_portfolio == 2:
            self.aidx = {'aS': np.arange(self.aS_dim)}
        if self.survey_is_action == 1:
            self.aidx['aY'] = np.arange(self.aY_dim)+self.aidx[list(self.aidx.keys())[-1]][-1]+1
        # initialize state and observation
        self.obs, self.state = self.reset()

    def reset(self):
        self.obs = np.zeros(self.obsspace_dim)
        self.state = np.zeros(self.statespace_dim)
        X = np.random.choice([0,1], size=self.X_dim, p=[0.3,0.7]) # initial occupancy state
        H = np.random.choice([0,1], size=self.H_dim, p=[self.deltaH, 1-self.deltaH]) # initial habitat quality
        Z = np.random.choice([0,1], size=self.Z_dim, p=[self.Ztrans[0,0], self.Ztrans[1,0]]) # initial dispersal regime
        if self.partial_observability == 1:
            M, Y = self.survey(X) # initial survey observation
            if self.dispersal_regime == 1:
                self.state = np.concatenate([X,H,M,Z,[0]])
            else: 
                self.state = np.concatenate([X,H,M,[0]])
            self.obs = np.concatenate([Y,H,M,[0]])
        else:
            if self.dispersal_regime == 1:
                self.state = np.concatenate([X,H,Z,[0]])
            else:
                self.state = np.concatenate([X,H,[0]])
            self.obs = np.concatenate([X,H,[0]])
        return self.obs, self.state
    
    def step(self, action):
        info = {}
        if self.action_portfolio == 0:
            aR = action[self.aidx['aR']]
            aS = action[self.aidx['aS']]
        elif self.action_portfolio == 1:
            aR = action[self.aidx['aR']]
            aS = np.zeros(self.aS_dim, dtype=int)
        elif self.action_portfolio == 2:
            aR = np.zeros(self.aR_dim, dtype=int)
            aS = action[self.aidx['aS']]
        aY = action[self.aidx['aY']] if self.survey_is_action == 1 else np.zeros(self.aY_dim, dtype=int)
        X = self.state[self.sidx['X']]
        H = self.state[self.sidx['H']]
        if self.dispersal_regime == 1:
            Z = self.state[self.sidx['Z']][0]
        else:
            Z = 0
        t = self.state[self.sidx['t']]
        # calculate colonization and extinction probabilities based on current state and parameters
        connectivity = self.w @ X # connectivity for each patch based on current occupancy and dispersal weights
        cprob = 1 - np.exp(-self.alph0 * connectivity * (1 + self.alphZ * Z) * (1 + self.alphH * H))
        eprob = (1/(1+np.exp(-(self.beta0 - self.betaH * H)))) * (1 - cprob)
        # update state based on actions and transition probabilities
        ## occupancy 
        X_next = np.zeros(self.X_dim, dtype=int)
        mask = X==0
        mask2 = ~mask
        X_next[mask] = np.random.binomial(1, cprob[mask]) + aS[mask] * np.random.binomial(1, self.qs, size=np.sum(mask))
        X_next[mask2] = np.random.binomial(1, 1 - eprob[mask2]) + aS[mask2] * np.random.binomial(1, self.qs, size=np.sum(mask2))
        X_next = np.minimum(X_next, 1)
        ## habitat quality
        H_next = np.zeros(self.H_dim, dtype=int)
        H_next[aR==1] = 1
        mask = (aR == 0) & (H == 1)
        H_next[mask] = np.random.choice([0,1], size=np.sum(mask), p=[self.deltaH, 1-self.deltaH])
        ## dispersal regime
        if self.dispersal_regime == 1:
            Z_next = np.random.choice([0,1], size=self.Z_dim, p=self.Ztrans[:,Z])
        # update observaiton based on new state and observation probabilities
        if self.partial_observability == 1:
            M_next, Y_next = self.survey(X_next) if self.survey_is_action == 0 else self.survey(X_next, survey_patches=aY)
            if self.dispersal_regime == 1:
                self.state = np.concatenate([X_next, H_next, M_next, Z_next, t+1])
                self.obs = np.concatenate([Y_next, H_next, M_next, Z_next, t+1])  
            else:
                self.state = np.concatenate([X_next, H_next, M_next])
                self.obs = np.concatenate([Y_next, H_next, M_next])
        else:
            if self.dispersal_regime == 1:
                self.state = np.concatenate([X_next, H_next, Z_next, t+1])
                self.obs = np.concatenate([X_next, H_next, Z_next, t+1])
            else:
                self.state = np.concatenate([X_next, H_next, t+1])
                self.obs = np.concatenate([X_next, H_next, t+1])
        self.state
        # reward
        reward = 1/self.patchnum * np.sum(X_next) - self.cr * np.sum(aR) - self.cs * np.sum(aS) # reward based on number of occupied patches and cost of actions

            # done
        if t == self.T-1:
            reward = reward - self.L * (np.sum(1 - X_next)) if self.terminal_penalty == 1 else reward # add terminal penalty
            done = True
        elif np.sum(X_next) == 0: # all patches are extinct
            done = True
        else:           
            done = False

        return self.obs, reward, done, info
        
    def survey(self,X, survey_patches = None):
        M = np.zeros(self.M_dim, dtype=int)
        if self.survey_is_action == 1:
            ones_indices = survey_patches == 1
        else:
            ones_indices = np.random.choice(self.M_dim, size=int(self.B), replace=False)
        M[ones_indices] = 1
        Y = np.zeros(self.Y_dim, dtype=int)
        Y[M==1] = X[M==1] * np.random.choice([1,0], size=np.sum(M), p=[self.pdet, 1-self.pdet]) + (1-X[M==1]) * np.random.choice([1,0], size=np.sum(M), p=[self.pfp, 1-self.pfp]) # initial survey observation
        return M, Y 
